name:                vimhs
version:             0.1.0.0
homepage:            https://github.com/uuhan/vimhs#readme
license:             BSD3
author:              uuhan
maintainer:          xuminhui189@gmail.com
category:            Neovim
extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - TemplateHaskell

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - file-embed
  - bytestring
  - containers
  - nvim-hs
  - nvim-hs-contrib
  - nvim-hs-ghcid
  - word8
  - parsec
  - curl
  - text
  - tagsoup
  - scalpel

executables:
  vimhs:
    source-dirs:
      - .
      - src
    main:        Main.hs
