name:                vimhs
version:             0.1.0.0
homepage:            https://github.com/uuhan/vimhs#readme
license:             BSD3
author:              uuhan
maintainer:          xuminhui189@gmail.com
category:            Neovim
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - file-embed
  - bytestring
  - containers
  - nvim-hs
  - nvim-hs-ghcid
  - word8

executables:
  vimhs:
    source-dirs:
      - .
      - src
    main:        Main.hs
    other-modules:
      - Neovim.Plugins.HackerNews.Plugin
      - Neovim.Plugins.HackerNews
      - Neovim.Plugins.Ghcmod.Plugin
      - Neovim.Plugins.Ghcmod
      - Neovim.Plugins.GLSL.Plugin
      - Neovim.Plugins.GLSL.Api
      - Neovim.Plugins.GLSL
