resolver: lts-8.13

packages:
  - .
  - location:
      git: https://github.com/neovimhaskell/nvim-hs
      commit: HEAD
    extra-dep: true
  - location:
      git: https://github.com/neovimhaskell/nvim-hs-contrib
      commit: HEAD
    extra-dep: true

extra-deps:
  - ../glsl-completation
  - ../nvim-hs-ghcid
