resolver: lts-8.13

packages:
  - .
  - location:
      git: https://github.com/uuhan/nvim-hs
      commit: HEAD
    extra-dep: true
  - location:
      git: https://github.com/neovimhaskell/nvim-hs-contrib
      commit: HEAD
    extra-dep: true
  - location:
      git: https://github.com/saep/nvim-hs-ghcid
      commit: HEAD
    extra-dep: true
